INFO     test_case:conftest.py:56 cap info: {'platformName': 'Android', 'automationName': 'UiAutomator2', 'platformVersion': '11', 'deviceName': 'c543cf80', 'appActivity': 'com.mega.chery.gallery.ui.ImageActivity', 'appPackage': 'com.mega.chery.gallery'}
INFO     test_case:conftest.py:72 启动app参数为: {'platformName': 'Android', 'automationName': 'UiAutomator2', 'platformVersion': '11', 'deviceName': 'c543cf80', 'appActivity': 'com.mega.chery.gallery.ui.ImageActivity', 'appPackage': 'com.mega.chery.gallery'}
INFO     test_case:conftest.py:188 
    初始化图库驱动
     成功
INFO     test_case:base_page.py:41 开始初始化驱动driver......
INFO     test_case:base_page.py:41 开始初始化驱动driver......
INFO     test_case:base_page.py:133 wait_locator: <appium.webdriver.webelement.WebElement (session="cad1af55-38fd-4283-acc3-22a2e3aa79c2", element="f6f840b0-e726-4f6b-9bfd-7c29b76d0a79")>
INFO     test_case:base_page.py:535 元素描述为: 图片中导出按钮
INFO     test_case:base_page.py:543 web_elem: <appium.webdriver.webelement.WebElement (session="cad1af55-38fd-4283-acc3-22a2e3aa79c2", element="e6239d64-75c4-41c4-9ad6-fa5e04beff30")>
INFO     test_case:base_page.py:555 图片中导出按钮 locator: ('id', 'com.mega.chery.gallery:id/exportBtn')
INFO     test_case:test_gallery.py:274 测试数据为: 未识别到
INFO     test_case:base_page.py:152 wait_locator: ('xpath', '//*[contains(@text, "未识别到")]')
INFO     test_case:base_page.py:411 获取toast成功: 未识别到可导出USB设备
INFO     test_case:test_gallery.py:279 错误提示为: 未识别到可导出USB设备
INFO     test_case:test_gallery.py:281 导出失败，无usb设备，测试异常导出图片成功
INFO     test_case:conftest.py:191 正在关闭驱动
INFO     test_case:conftest.py:193 关闭驱动成功！